language: node_js
node_js:
  - "10.3.0"

addons:
  ssh_known_hosts:
    - github.com

stages:
  - build
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    - stage: build
      node_js:
        - "10.3.0"
      script:
        - npm run build
    - stage: test
      node_js:
        - "10.3.0"
      script:
        - npm run test:coverage
    - stage: deploy
      node_js:
        - "10.3.0"
      script:
        - echo -e "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN\n" > ~/.npmrc
        - echo -e "machine github.com\n  login $CI_USER\n  password $CI_USER_PASSWORD\n" > ~/.netrc
        - npm version patch -m "Version %s [skip ci]"
        - git push origin HEAD:master
        - git push --tags
        - npm run patch-readme --silent > NEW-README.md
        - mv NEW-README.md README.md
        - npm publish
